server:
  port: 8086
feign:
  okhttp:
    enabled: true
  sentinel:
    enabled: true

mall:
  swagger:
    title: "eMall order service API"
    package: com.ecomm.order.controller
  db:
    database: hm-trade

spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8090
      http-method-specify: true # for same endpoint but different method
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: 654321

