server:
  port: 8081


mall:
  swagger:
    title: "eMall item service API"
    package: com.ecomm.item.controller
  db:
    database: hm-item

spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8090
      http-method-specify: true # for same endpoint but different method
