server:
  port: 8083
feign:
  okhttp:
    enabled: true
  sentinel:
    enabled: true

mall:
  swagger:
    title: "eMall cart service API"
    package: com.ecomm.cart.controller
  db:
    database: hm-cart

spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8090
      http-method-specify: true # for same endpoint but different method
